site_name: SSE Documentation Example

nav: 
    - Home: 'index.md'
    - 'User Guide':
        - 'Installation': 'compilation-and-installation.md'
        - 'Getting Started': 'how-to.md'

repo_url: https://github.com/kimkroener/mkdocs-exercise

edit_uri: edit/main/docs/

site_author: kimkroener

extra_css: [extra.css]